### ISSUE TITLE
Most of the domains are not working.

### ISSUE THREAD

**Issue by qwexvf** [jshmrtn/email_checker#13]
# What's happening
Hi. i was trying this cool module but most of the domains (gmail, yahoo, outlook) are failing for some reason.
i tried debugging my self but couldn't get to the point of where might be wrong.
one thing i tried is telnetting to gmail

```
telnet gmail-smtp-in.l.google.com 25      
Trying 2404:6800:4008:c07::1a...
Connection failed: Permission denied
Trying 64.233.189.26...
telnet: Unable to connect to remote host: No route to host
```

 Any suggestions? Thanks.

Edit:
Sorry i didn't read correctly the readme page which says
`Most email providers nowadays don't support this method. You should only use it if you know what you're doing.`

Is there any alternative way to do this?..

**Comment by qwexvf** [comment]
Sorry figure out myself where was wrong! All working now <3

**Comment by lechuhuuha** [comment]
> Sorry figure out myself where was wrong! All working now <3

Hi if you dont mind can you share the alternative method you had figure out?
Thanks in advanced!
